baraBulka: test3 ci schema

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,1 +1,3 @@
-npx --no -- commitlint --edit $1
+echo "CommitLint..."
+(npx --no-install commitlint --edit "$1") || (echo "CommitLint failed!"; exit 1)
+echo "CommitLint successful!"
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -11,5 +11,5 @@ echo "Building..."
 echo "Build successful!"
 
 echo "e2e testing..."
-(npm run test:e2e 1> /dev/null) || (echo "e2e testing failed"; exit 1)
+(npm run test:e2e 1> /dev/null) || (echo "e2e testing failed!"; exit 1)
 echo "e2e testing successful!"
