ci: test ci schema

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,7 @@
+echo "CommitLint..."
+(npm run format 1> /dev/null) || (echo "Formatting failed!"; exit 1)
+echo "Formatting successful!"
+
 echo "Formatting..."
 (npm run format 1> /dev/null) || (echo "Formatting failed!"; exit 1)
 echo "Formatting successful!"
